<html> 
      <head>
        <title>GAP (ref) - Chapter 6: Main Loop and Break Loop &amp;#8614; 6.6-1 Error</title>
        <meta name="url" content="http://www.gap-system.org/Manuals/doc/ref/chap6_mj.html#X7E7AD8D87EBA1A08"></meta>
      </head>
      <body> <h5 xmlns="http://www.w3.org/1999/xhtml">6.6-1 Error</h5><div class="func" xmlns="http://www.w3.org/1999/xhtml"><table width="100%" class="func"><tbody><tr><td colspan="1" rowspan="1" class="tdleft"><code class="func">‣ Error</code>( <var class="Arg">messages</var>, <var class="Arg">...</var> )</td><td colspan="1" rowspan="1" class="tdright">( function )</td></tr></tbody></table></div><p xmlns="http://www.w3.org/1999/xhtml"><code class="func">Error</code> signals an error from within a function. First the messages <var class="Arg">messages</var> are printed, this is done exactly as if <code class="func">Print</code> (<a shape="rect" href="chap6_mj.html#X7AFA64D97A1F39A3"><span class="RefLink">6.3-4</span></a>) (see <a shape="rect" href="chap6_mj.html#X8074A8387C9DB9A8"><span class="RefLink">6.3</span></a>) were called with these arguments. Then a break loop (see <a shape="rect" href="chap6_mj.html#X8593B49F8705B486"><span class="RefLink">6.4</span></a>) is entered, unless the standard error output is not connected to a terminal. You can leave this break loop with <code class="code">return;</code> to continue execution with the statement following the call to <code class="func">Error</code>. <code class="func">ErrorNoReturn</code> (<a shape="rect" href="chap6_mj.html#X7A5C000D7E4984DD"><span class="RefLink">6.6-2</span></a>) operates identically to <code class="func">Error</code>, except it does not allow using <code class="code">return;</code> to continue execution.</p> </body>
    </html>